### PR TITLE
Fix for real time logging (create new response condition) issue #682

### LINKED ISSUE #682: Bug on Fastly module UI
Hello Fastly Team, 

Multiple customers are raising this issue as a bug. 

Unable to add log shipping jobs due to a bug on Fastly Magento UI that is not saving 

When we add the condition and create it is not saving. 

Steps to Reproduce: stores>configuration> advanced > system > tools> attach condition  > create new response condition> name and give logic > click create > create go back onto it condition is missing

Customer is on the following fastly module version: 

1.2.210

Please note this issue is with fastly module so please investigate this from your side. 

Customer is on 
fastly magento issue (2)

Thanks 
Ishwar

### PR DESCRIPTION
**Pull request by dpotkoc**
this closes #682

### CODE REVIEW

**Comment by vvuksan** [comment]
It's part of 1.2.211

**Comment by ikhadka** [comment]
Hello Team, 

@vvuksan 

One of you merchant has tested this on their side and please review their feedback: We’ve updated the extension in the staging environment, tested and confirmed that the issue is partially resolved. We’re now able to attach a logging condition to a new logging endpoint when we first create it, but when we edit it, the new condition is not showing in the condition dropdown (it’s just blank). We’ve also verified that the condition is written to the generated VCL correctly.

This solution, as it stands right now, will allow us to proceed with our work, but it would be nice to be able to make changes in the future as well.

Thanks

**Comment by dpotkoc** [comment]
thnx @ikhadka we will check it.

**Comment by dpotkoc** [comment]
@ikhadka new fix is added in https://github.com/fastly/fastly-magento2/pull/684

**Pull request merged**
