### PR TITLE
Real-Time Log streaming fix #682

### LINKED ISSUE #682: Bug on Fastly module UI
Hello Fastly Team, 

Multiple customers are raising this issue as a bug. 

Unable to add log shipping jobs due to a bug on Fastly Magento UI that is not saving 

When we add the condition and create it is not saving. 

Steps to Reproduce: stores>configuration> advanced > system > tools> attach condition  > create new response condition> name and give logic > click create > create go back onto it condition is missing

Customer is on the following fastly module version: 

1.2.210

Please note this issue is with fastly module so please investigate this from your side. 

Customer is on 
fastly magento issue (2)

Thanks 
Ishwar

### PR DESCRIPTION
**Pull request by dpotkoc**
this is related to #682

### CODE REVIEW

**Comment by ikhadka** [comment]
Thank you @dpotkoc we will test this on our side and get back to you. Thanks

**Comment by ikhadka** [comment]
Hello @dpotkoc 

Our SRE team have tested this issue and this is still not resolved. Same issue as before. Please could you look into this. Thanks

**Comment by ikhadka** [comment]
Hello @dpotkoc 

I hope you are well ! Just wanted to check if you had any update on this. 

Thanks 
Ishwar

**Comment by dpotkoc** [comment]
@ikhadka we tested PR modification https://github.com/fastly/fastly-magento2/pull/684 with new relic log streaming.

Currently we can't reproduce issue, please could you send me instruction in steps how to reproduce issue.

and question did you test on last modifications from this PR?

**Comment by ikhadka** [comment]
Hello @dpotkoc 

Thank you for looking in to this one. We have now tested this with our SRE team and it resolves the issue. Please could you push this to live and do let me know the version customer needs to upgrade to. Thanks

**Pull request merged**
