### PR TITLE
Netacea Fastly/Magento module - URL paths ignore list

### PR DESCRIPTION
**Pull request by mizdebski-netacea**
The goal of this PR is to introduce a new URL paths ignore functionality to Netacea Fastly/Magento module. 

Changes include:
- New, optional configuration field in Magento Netacea's module 
- New Netacea's config field
- Logic of ignoring URL paths that are specified in the config
- Integration type and VCL version changes
- Version bump

### CODE REVIEW

**Comment by bbutkovic** [comment]
Hey @mizdebski-netacea we had some updates to our tests, could you please merge the latest `master` branch into your branch?

**Comment by mizdebski-netacea** [comment]
> 

@bbutkovic merged now.

**Comment by mizdebski-netacea** [comment]
@bbutkovic is there any chance this could be merged today? I wouldn't like to hurry anybody but I'd really appreciate that :)

**Comment by mizdebski-netacea** [comment]
@bbutkovic @vvuksan deep apologies for tagging you and being a pain but it's really an urgent matter for us and would mean a lot if this could be merged. I know you have a ton of work but maybe there is some likelihood that you will have some free time for this case 🥲

**Comment by bbutkovic** [comment]
@mizdebski-netacea We will discuss this internally and let you know :)

**Comment by mizdebski-netacea** [comment]
> @mizdebski-netacea We will discuss this internally and let you know :)

Thank you kind sir!

**Comment by vvuksan** [comment]
Hi @mizdebski-netacea. It appears in this release you are referring to Netacea_Config edge dictionary in recv and deliver snippets. Currently it's not possible to create edge dictionaries via Edge Modules so how will this be added to the user's config since without it this VCL will error out and not activate.

**Comment by vvuksan** [comment]
Disregard previous message. It appears you have changed the default behavior for the module to be INGEST instead of MITIGATE. Is that expected ?

**Comment by mizdebski-netacea** [comment]
> Disregard previous message. It appears you have changed the default behavior for the module to be INGEST instead of MITIGATE. Is that expected ?

I am very thankful for this wonderful spot! Thank you very much. Changed it right now back to MITIGATE.

**Comment by vvuksan** [comment]
It's been released in 1.2.196+

**Pull request merged**
